extends:
  - stylelint-config-standard
  - '@stylistic/stylelint-config'

plugins:
  - ./node_modules/@rhds/tokens/plugins/stylelint.js
  - '@stylistic/stylelint-plugin'

ignoreFiles:
  - node_modules/**/*
  - docs/assets/javascript/elements/*.js

rules:
  alpha-value-notation: number # TODO: fix for `percentage` in tokens
  color-hex-length: long

  # TODO: fix this in tokens plugin
  # color-function-notation: modern
  color-function-notation: null

  # Disabled after upgrade to stylelint-config-standard v39.
  # These rules create conflicts with design token values and valid CSS patterns.

  # Tokens may contain rgba/hsla syntax which v39 rejects in favor of rgb/hsl
  color-function-alias-notation: null

  # Tokens may reference deprecated but still-supported properties
  # (clip, word-wrap, grid-gap, grid-column-gap, etc.)
  property-no-deprecated: null

  # Token values may use syntax that stylelint doesn't recognize but browsers support
  declaration-property-value-no-unknown: null

  # Token values may use deprecated keywords that remain functional (e.g., break-word)
  declaration-property-value-keyword-no-deprecated: null

  # Avoid conflicts with valid descriptors in @font-face (e.g., text-rendering)
  at-rule-descriptor-no-unknown: null

  custom-property-pattern: _?[a-z]+[a-z0-9-]*
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands:
        - /grid/

  media-feature-range-notation: prefix
  number-max-precision: 6
  no-descending-specificity:
    - true
    - ignore:
      - selectors-within-list
  selector-class-pattern: null
  selector-pseudo-element-colon-notation: single
  shorthand-property-no-redundant-values: true
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
      ignoreTypes:
        - heading
        - actions
        - pending
        - --rendered

  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
      - /part(.*)/

  '@stylistic/string-quotes': single
  '@stylistic/selector-combinator-space-after': always
  '@stylistic/selector-combinator-space-before': always
  '@stylistic/function-parentheses-newline-inside': null
  '@stylistic/function-comma-newline-after': always-multi-line
  '@stylistic/indentation':
    - 2
    - indentInsideParens: 'once-at-root-twice-in-block'
  '@stylistic/max-line-length':
    - 100
    - ignorePattern: /(--rh-font-family-|https:\/\/)/

  rhds/deprecated: true
  rhds/token-values: true

  rhds/no-unknown-token-name:
    - true
    - allowed:
      - --rh-icon-size
      - --rh-navigation-active-item-color
      - --rh-jump-link-max-width

overrides:
  - files:
      - docs/**/*.scss
    defaultSeverity: warning
    extends: stylelint-config-standard-scss
    rules:
      '@stylistic/block-closing-brace-newline-after': null
      scss/at-if-closing-brace-newline-after: always-last-in-chain
      '@stylistic/max-line-length':
        - 120
        - ignorePattern: /--rh-font-family-/

