extends:
  - stylelint-config-standard
  - '@stylistic/stylelint-config'

plugins:
  - ./node_modules/@rhds/tokens/plugins/stylelint.js
  - '@stylistic/stylelint-plugin'

ignoreFiles:
  - node_modules/**/*
  - docs/assets/javascript/elements/*.js

rules:
  alpha-value-notation: number # TODO: fix for `percentage` in tokens
  color-hex-length: long

  # TODO: fix this in tokens plugin
  # color-function-notation: modern
  color-function-notation: null

  custom-property-pattern: _?[a-z]+[a-z0-9-]*
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands:
        - /grid/

  media-feature-range-notation: prefix
  number-max-precision: 6
  no-descending-specificity:
    - true
    - ignore:
      - selectors-within-list
  selector-class-pattern: null
  selector-pseudo-element-colon-notation: single
  shorthand-property-no-redundant-values: true
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
      ignoreTypes:
        - heading
        - actions
        - pending
        - --rendered

  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
      - /part(.*)/

  '@stylistic/string-quotes': single
  '@stylistic/selector-combinator-space-after': always
  '@stylistic/selector-combinator-space-before': always
  '@stylistic/function-parentheses-newline-inside': never-multi-line
  '@stylistic/function-comma-newline-after': always-multi-line
  '@stylistic/indentation':
    - 2
    - indentInsideParens: 'once-at-root-twice-in-block'
  '@stylistic/max-line-length':
    - 100
    - ignorePattern: /(--rh-font-family-|https:\/\/)/

  rhds/deprecated: true
  rhds/token-values: true

  rhds/no-unknown-token-name:
    - true
    - allowed:
      - --rh-icon-size
      - --rh-navigation-active-item-color

overrides:
  - files:
      - docs/**/*.scss
    defaultSeverity: warning
    extends: stylelint-config-standard-scss
    rules:
      '@stylistic/block-closing-brace-newline-after': null
      scss/at-if-closing-brace-newline-after: always-last-in-chain
      '@stylistic/max-line-length':
        - 120
        - ignorePattern: /--rh-font-family-/

