extends:
  - stylelint-config-standard
  - stylelint-stylistic/config

ignoreFiles:
  - node_modules/**/*

rules:
  alpha-value-notation: number # TODO: fix for `percentage` in tokens
  color-hex-length: long

  # TODO: fix this in tokens plugin
  # color-function-notation: modern
  color-function-notation: null

  custom-property-pattern: _?[a-z]+[a-z0-9-]*
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands:
        - /grid/

  number-max-precision: 6
  no-descending-specificity:
    - true
    - ignore:
      - selectors-within-list
  selector-class-pattern: null
  selector-pseudo-element-colon-notation: single
  shorthand-property-no-redundant-values: true
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
      ignoreTypes:
        - heading
        - actions

  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
      - /part(.*)/

  stylistic/string-quotes: double
  stylistic/selector-combinator-space-after: always
  stylistic/selector-combinator-space-before: always
  stylistic/indentation:
   - 2
   - indentInsideParens: 'once-at-root-twice-in-block'
  stylistic/max-line-length:
    - 100
    - ignorePattern: /--rh-font-family-/

  rhds/token-values: true
  rhds/no-unknown-token-value:
    - true
    - migrations:
      # grays
      --rh-color-gray-05: --rh-color-gray-10
      --rh-color-gray-10: --rh-color-gray-20
      --rh-color-gray-20: --rh-color-gray-30
      --rh-color-gray-30: --rh-color-gray-40
      --rh-color-gray-40: --rh-color-gray-50
      --rh-color-gray-50: --rh-color-gray-60
      --rh-color-gray-60: --rh-color-gray-70
      --rh-color-gray-70: --rh-color-gray-80
      --rh-color-gray-80: --rh-color-gray-90
      --rh-color-gray-90: --rh-color-gray-95
      --rh-color-black: --rh-color-gray-100


  media-feature-range-notation: prefix

plugins:
  - ./node_modules/@rhds/tokens/plugins/stylelint.cjs
  - stylelint-stylistic

overrides:
  - files:
      - docs/**/*.scss
    defaultSeverity: warning
    extends: stylelint-config-standard-scss
    rules:
      stylistic/max-line-length:
        - 120
        - ignorePattern: /--rh-font-family-/

