extends: stylelint-config-sass-guidelines
defaultSeverity: warning
rules:
  selector-pseudo-element-colon-notation: single
  max-line-length:
    - 120
    - ignorePattern: /--rh-font-family-/

  max-nesting-depth:
    - 3
    - ignore:
      - pseudo-classes
      ignoreAtRules:
      - each
      - media
      - supports
      - include

  selector-class-pattern: null
  indentation: 2
  string-quotes: single
  shorthand-property-no-redundant-values: true
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  custom-property-pattern: _.*|rh-

overrides:
  - files:
      - elements/**/*.css
    extends: stylelint-config-standard

    ignoreFiles:
      - node_modules/**/*

    rules:
      rhds/token-values:
        - true

      selector-type-no-unknown:
        - true
        - ignore:
          - custom-elements
          ignoreTypes:
          - heading
          - actions

      selector-pseudo-element-no-unknown:
        - true
        - ignorePseudoElements:
          - /part(.*)/

    plugins:
      - ./node_modules/@rhds/tokens/plugins/stylelint.cjs
