extends: stylelint-config-standard
ignoreFiles:
  - node_modules/**/*

rules:
  selector-pseudo-element-colon-notation: single
  selector-class-pattern: null
  indentation: 2
  string-quotes: single
  shorthand-property-no-redundant-values: true
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  custom-property-pattern: _.*|rh-
  max-line-length:
    - 100
    - ignorePattern: /--rh-font-family-/
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
      ignoreTypes:
        - heading
        - actions

  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
      - /part(.*)/

  rhds/token-values: true

plugins:
  - ./node_modules/@rhds/tokens/plugins/stylelint.cjs

overrides:
  - files:
      - docs/**/*.scss
    extends: stylelint-config-sass-guidelines
    defaultSeverity: warning
    rules:
      max-line-length:
        - 120
        - ignorePattern: /--rh-font-family-/

