name: 🧰 Ready for Development
description: Design-to-development handoff checklist
title: '[feat]: <title> ready for development'
labels:
  - new component
  - ready for development

body:
  - type: markdown
    attributes:
      value: >-
        ## Introduction
        **Working with a developer to build components should never be a guessing
        game**. Providing them with documentation will ensure your component is
        developed as you intend.

        ## Who is this checklist for?
        This checklist is **intended for designers to fill out when they are
        creating component documentation** for developers. It is also **intended for
        developers who are not sure of what specific documentation to reference**
        when building your component.

        ## Why do we need this checklist?
        Having a designer provide consistent documentation to a developer will
        **eliminate guessing games and assumptions** made about how to correctly
        develop your component.

        ## How to use this checklist
        When your component design is final and approved, **use this checklist to
        determine the right amount of documentation specs to include for a
        developer**.

        You may fill out this checklist on your own or you can **work closely
        with the assigned developer and fill out this checklist together** in order
        to determine exactly what documentation specs they need. Starting in the
        Appearance section, check the box next to each spec after you add it to
        your primary XD source file. **Not every spec is required to include**, some
        specs only apply to complex components because they require more
        documentation.

        -----

        ## About Required Fields
        Some of the fields in this form are required, e.g. the accessibility
        requirements. You _won't be able to submit the issue_ until they are
        checked. You may however draft the descriptive fields using Google Docs
        and paste the formatted text into the text areas here. Simple formatting
        like bold, links, etc. should be preserved. Learn more about using
        [GitHub-flavoured Markdown](gfmmd) on the GitHub docs.

  - type: input
    id: tag
    attributes:
      label: Tag Name
      description: What will be the HTML tag for this element
      placeholder: rh-jazz-hands
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: Explain the purpose of your component or the business need for its creation
      placeholder: >-
        My component needs to be created in order to track the progress of a
        user through the trial signup process (rh-progress-steps).
    validations:
      required: true

  - type: textarea
    id: distinguishing-factors
    attributes:
      label: Distinguishing factors
      description: If your component feels similar to an existing component, describe how it is different
      placeholder: >-
        My Button component feels similar to a Call to action, but a Button is
        visually smaller and performs an action whereas a Call to action is
        visually larger and directs a user to another page
        (`rh-button` and `rh-call-to-action`).
    validations:
      required: false

  - type: textarea
    id: intended-use-context
    attributes:
      label: Where will it be used?
      description: Describe the website, web property, or layout where your component will be used
      placeholder: >-
        My component will be used on pages where a user can browse through
        content listings or search results (`rh-pagination`).
    validations:
      required: true

  - type: textarea
    id: end-user
    attributes:
      label: End user
      description: Describe the end user or audience who will use your component
      placeholder: >-
        An analyst or user who needs to browse through pages of content listings or
        search results on any device (rh-pagination).
    validations:
      required: true

  - type: textarea
    id: intended-use
    attributes:
      label: Intended end use
      description: >-
        Describe how a user should use your component or any intended actions or features
      placeholder: >-
        A user should be able to select a different content listing page or
        type which page they want to navigate to in a text field (`rh-pagination`)
    validations:
      required: true

  - type: textarea
    id: properties
    attributes:
      label: Properties
      description: >-
        Describe any controls, properties, or variants your component may need
      placeholder: >-
        My button component nees sizes: `small` and `large`

  - type: checkboxes
    id: page-builder
    attributes:
      label: Page Builder?
      description: >-
        Is your component going to be a part of a page builder experience?
      options:
        - label: yes

  - type: checkboxes
    id: a11y
    attributes:
      label: Accessibility Features
      description: >-
        Ensure that the following accessibility features have been address in
        design. For more information see [WCAG 2.0](wcag2), [WAI-ARIA examples](waiae),
        and [MDN Intro to Color and A11y](mdnco).

        **👉 If a requirement is not applicable, mark it as checked. 👈**

      options:
        - label: '**Color** should not be the primary visual means of communicating information ([1.4.1](1.4.1))'
          required: true
        - label: '**Content or microcopy** in any language should be clear, meaningful, structured, etc.'
          required: true
        - label: '**Text Contrast**: Small text should have a contrast ratio of at least 4.5:1 ([1.4.3](1.4.3))'
          required: true
        - label: '**Text Contrast**: Large text should have a contrast ratio of at least 3:1 ([1.4.3](1.4.3))'
          required: true
        - label: '**Resizable Text**: Text should have the ability to be **resized** up to 200% without losing content or functionality (for example, horizontal scrolling) ([1.4.4](1.4.4))'
          required: true
        - label: '**Alt Text**: Non-text elements should have concise **text descriptions** (a.k.a. **alt text**) ([1.1.1](1.1.1))'
          required: true
        - label: '**Keyboard**: Descriptions of how interactive elements behave when a key is pressed should be included ([2.1.1](2.1.1)) (for example, the Esc key closes a navigation menu)'
          required: true
        - label: '**Focus Appearance**: Colors between **focused states** should have a contrast ratio of at least 3.1 ([2.4.11](2.4.11))'
          required: true
        - label: '**Focus Appearance**: Borders should have a thickness of at least 2px ([2.4.11](2.4.11))'
          required: true
        - label: '**Focus Order**: It should be logical how a user moves focus from one element to another ([2.4.3](2.4.3))'
          required: true
        - label: '**Motion Animation**: Controls should be available to disable an animation triggered by an interaction ([2.3.3](2.3.3))'
          required: true
        - label: '**Mobile**: Interactive elements should be reachable for touching, scrolling, or dismissing'
          required: true

  - type: checkboxes
    id: mvp
    attributes:
      label: MVP Requirements
      description: >-
        At minimum, these specs should always be included for a component of any size.
        If you have more time to include more specs, please do so.
      options:
        - label: Correct styles and neccessary sizes, orientations, variants, spacers, and themes
          required: true
        - label: Responsive sizes and page layout examples placed on screenshots
          required: true
        - label: Functionality guidance and static animation frames or prototypes with motion
          required: true
        - label: Interaction and Selected states
          required: true
        - label: Alignment options, character counts, and necessary translations
          required: true
        - label: Clear and structured content, acceptable text contrast, and logical keyboard events
          required: true

  - type: checkboxes
    id: appearance
    attributes:
      label: Appearance
      description: >-
        The properties and visual language that define your component, see examples [here](https://xd.adobe.com/view/98f8d0b4-12e1-4377-b92b-e3d5d226eda1-cdab/?fullscreen)
      options:
        - label: Foundations are represented as tokens or variables (border, color, font, opacity, spacing, shadow, etc.) [Consult with the assigned developer to ensure you are both working with the correct styles and values]
          required: false
        - label: Foundations are applied to elements (backgrounds, buttons, fields, icons, links, etc.)
          required: false
        - label: Size (Standard, Compact, Mini, etc.)
          required: false
        - label: Orientations (horizontal or vertical)
          required: false
        - label: Position in relation to trigger (top, right, bottom, left, etc.)
          required: false
        - label: Hierarchy and decoration variants (Primary and Secondary CTAs, Earth and Wind variant Tabs, etc.)
          required: false
        - label: Decorations (borders, logos, UI icons, etc.)
          required: false
        - label: Desktop and mobile scale spacers (visit the [Spacing](https://ux.redhat.com/foundations/spacing/) and [Typography](https://ux.redhat.com/foundations/typography/) pages for examples)
          required: false
        - label: Themes (light, dark, high-contrast, custom color, etc.)
          required: false
        - label: Edge cases or limitations (accessibility, brand extensions, horizontal scrolling, missing images, etc.) [It is not required to include all of these specs, but keep them in mind]
          required: false
        - label: Fallback (if a browser does not support the original design) [Consult with the assigned developer first to determine if this is necessary to design]
          required: false

  - type: markdown
    attributes:
      value: |
        [1.4.1]: https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html
        [1.4.3]: https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html
        [1.4.4]: https://www.w3.org/WAI/WCAG22/Understanding/resize-text.html
        [1.1.1]: https://www.w3.org/WAI/WCAG22/Understanding/non-text-content.html
        [2.1.1]: https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html
        [2.4.11]: https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum.html
        [2.3.3]: https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html
        [2.4.3]: https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html

        [wcag2]: https://www.w3.org/TR/WCAG20/
        [waiae]: https://www.w3.org/TR/wai-aria-practices/examples/
        [mdnco]: https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_Colors_and_Luminance
        [gfmmd]: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/about-writing-and-formatting-on-github

