name: 🪄 Feature request
description: Request a new feature in an existing component or pattern
title: "[feat] `<rh-component-name>` ..."
labels:
  - feature
  - discovery needed

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the new feature should do
      placeholder: >-
        `<rh-jazz-hands>` should be let users choose the era of Jazz the element represents
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
      description: >-
        Describe the solution you'd like: a clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: >-
        If applicable, add screenshots of examples in the wild
      placeholder: >-
        Copy/paste or drag screenshots into this textarea 
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example API
      description: >-
        If possible, provide an example HTML snippet of how you expect the new feature might work
      placeholder: >-
        <rh-jazz-hands era="ragtime"></rh-jazz-hands>
      render: HTML
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: >-
        Add any other context or screenshots about the feature request here.
