name: 🤖 Feature request
description: Request a new feature in an existing component
title: "[feat] <title>"
labels:
  - enhancement

body:

- type: textarea
  id: description
  attributes:
    label: Description
    description: >-
      A clear and concise description of what the new feature should do
    placeholder: >-
      `<rh-jazz-hands>` should be let users choose the era of Jazz the element represents
  validations:
    required: true

- type: textarea
  id: solution
  attributes:
    label: Suggested solution
    description: >-
      Describe the solution you'd like: a clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  id: example
  attributes:
    label: Example API
    description: >-
      Provide and example HTML snippet of how you expect the new feature might work
    placeholder: >-
      <rh-jazz-hands era="ragtime"></rh-jazz-hands>
    render: HTML
  validations:
    required: false

- type: textarea
  id: additional-info
  attributes:
    label: Additional context
    description: >-
      Add any other context or screenshots about the feature request here.
